### ISSUE TITLE
Not working with Superagent 1.7.2?

### ISSUE THREAD

**Issue by micros123** [Brightspace/superagent-d2l-promise-queue#7]
I'm trying to use this library in my ES6 React project, but it won't work. The library is loaded but it does not seem to attach itself to Superagent.

> Uncaught TypeError: _superagent2.default.post(...).send(...).useQueue is not a function

`import request from 'superagent';
import 'superagent-d2l-queue';
...
request
    .post('/api/tests')
    .send({
        info: 'example'
    })
    .useQueue()
    .end(...)
`

**Comment by mdedys** [comment]
There is a problem currently with it for version of superagent > 1.2. I will look into fixing this. If you use superagent 1.2 it will work

**Comment by mdedys** [comment]
#8 will fix the issue with different super agent versions not working.
